feat: allow restricting to namespace
cert-manager/aws-privateca-issuer pull request #247
Opened 2023-02-16 16:41 UTC by woehrl01

This PR adds the possibility to restrict to listening only to specific namespaces. This is required if you have use IAM role for service account. Otherwise this would allow you to create any AWSPCAIssuer in any namespace and resolve that with the controllers permission.

2023-02-16 18:08 UTC, woehrl01 commented
/assign @irbekrm

2023-02-16 19:51 UTC, kollabpr requested changes
Can you please add unit tests for the changes you have committed?

2023-02-16 20:02 UTC, woehrl01 commented
@kollabpr What exactly do you want me to write a unit test for? The set variable is from the `operator-sdk` and out of scope of this controller.

2023-02-16 20:11 UTC, divyansh-gupta commented
Hi @woehrl01 - Thanks for the feature request and the PR! We will review with the team and get back to you soon. In the meantime, we would love to know more about your use-case, how you are using the plugin and why you need this feature, to help us better make this decision. Please feel free to include any supporting documentation or steps you did.

2023-02-16 20:17 UTC, woehrl01 commented
I'm currently using the aws-privateca-issuer to issue certificates via an AWS Private CA. However, I want to limit the creation of certificates to a single application within a specific namespace while also leveraging IAM Roles for Service Accounts.

The current setup is not entirely secure because the controller assumes a role independently of the location of the AWSPCAIssuer. Therefore, I added additional restrictions so that the controller only operates within the trusted AWSPCAIssuer's namespace.

By implementing this additional restriction, I can ensure that the controller only listens to the single namespace where the trusted AWSPCAIssuer resides, ultimately improving the overall security of my system.

2023-02-21 18:28 UTC, divyansh-gupta commented
Hi @woehrl01 - have you tried using a regular issuer (not a ClusterIssuer) with the namespace set? https://github.com/cert-manager/aws-privateca-issuer/blob/main/config/samples/awspcaissuer_ec/_v1beta1_awspcaissuer_ec.yaml#L5

2023-02-21 18:37 UTC, woehrl01 commented
@divyansh-gupta of course that's what I use. But without this change you can generate this in any namespace and still issue with the role of the controller.

2023-02-21 20:49 UTC, divyansh-gupta commented
@woehrl01 Thank you for the response.

2023-02-27 16:53 UTC, divyansh-gupta commented
Adding details for how to reproduce after a chat with @woehrl01 -

Install the controller in Namespace1 (which contains a ServiceAccount with the correct IAM permissions attached), and then you create an issuer in Namespace2. Next, if you create a cert in Namespace2, the cert will still issue even though Namespace2 doesn't have the permissions necessary since the IAM role was attached to Namespace1.

We will move forward with trying to reproduce this.

2023-03-01 19:47 UTC, woehrl01 commented
@divyansh-gupta yes, exactly!

2023-03-07 17:22 UTC, divyansh-gupta commented
@woehrl01 We were able to reproduce this namespacing issue and were able to apply your patch and test the fix. Your fix works, however our team is still discussing alternatives and next steps.

For example, we noticed that other cert-manager issuers are not supporting this feature, and are looking into that.

2023-03-07 17:35 UTC, woehrl01 commented
@divyansh-gupta thanks for the update, can you please elaborate which alternatives you are discussing?

I'm not sure if other issuers suffer of the same attack surface as this only affects issuers which use an iam role for authentication, I'm not aware of any other issuers using that.

2023-04-08 15:34 UTC, woehrl01 commented
@divyansh-gupta are there any updates from your side regarding this PR?

2023-04-11 19:38 UTC, divyansh-gupta commented
@woehrl01 Hi there, we decided this approach makes sense. We haven't merged it due to having no automated tests for this scenario yet. This is something we would have to build before merging this PR.

2023-05-21 06:40 UTC, woehrl01 commented
Any updates on this @divyansh-gupta? Thank you!

2023-05-22 14:07 UTC, divyansh-gupta commented
Hi @woehrl01 - This work hasn't been prioritized on the team yet, I will keep you updated when we do. I appreciate your patience.

2023-07-30 13:01 UTC, woehrl01 commented
Hi @divyansh-gupta is there any progress on your side regarding to having this PR merged? Thanks!

2023-10-06 10:48 UTC, woehrl01 commented
For other readers. We have now replaced this change with using[ cert-manager/approver-policy](https://github.com/cert-manager/approver-policy):

*please adapt the allowed fields to your needs.

```yaml
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: aws-pca-issuers
spec:
  allowed:
    commonName:
      required: true
      value: "*"
    isCA: true
    subject:
      countries:
        required: true
        values:
          - '*'
      organizationalUnits:
        required: true
        values:
          - '*'
      organizations:
        required: true
        values:
          - '*'
  selector:
    issuerRef:
      group: awspca.cert-manager.io
      kind: AWSPCAIssuer
      name: awspca-issuer
    namespace:
      matchNames:
        - istio-system

```

2025-02-14 15:32 UTC, shankara-n commented
Hi @woehrl01, have you considered using RBAC to restrict namespaces? There is a flag in values.yaml to disable RBAC creation by aws-privateca-issuer. You can disable that and then create it manually with restrictions. 

Restricting access using RBAC seems more foolproof than restricting access from within the controller code.

2025-02-14 15:38 UTC, woehrl01 commented
@shankara-n No, I haven't, but that's of course a much cleverer way. Thanks for pointing that out. 😄

2025-09-04 18:48 UTC, anbaig commented
Closing this as it seems like RBAC will work without writing controller changes. Please re-open if you think this change is still needed.

2025-09-04 18:48 UTC, closed without merging