Arbitrary aws keys from secret
cert-manager/aws-privateca-issuer pull request #37
Opened 2021-07-08 18:21 UTC by marshields

2021-07-08 19:07 UTC, marshields commented
/assign @maelvls

2021-07-23 20:29 UTC, RedbackThomson requested changes
Hey, great job on this. I can absolutely see the value in this addition, and your tests do a solid job of demonstrating that. I have left some inline comments about how we can re-use some existing k8s core types.

2021-07-23 20:29 UTC, RedbackThomson commented on pkg/api/v1beta1/awspcaissuer_types.go
> +	SecretAccessKeySelector SecretSelector `json:"secretAccessKeySelector,omitempty"`
Have you thought about including the `AWS_SESSION_TOKEN` key as well? It's a slim chance, but I could imagine that the values inside a secret are generated through an `sts assume-role`, and therefore would require this additional key.

2021-07-23 20:29 UTC, RedbackThomson commented on pkg/api/v1beta1/awspcaissuer_types.go
> +type SecretReference struct {
My suggestion would be that this class composes the `SecretReference` type (https://pkg.go.dev/k8s.io/api/core/v1#SecretReference) and also is renamed.
```suggestion
type AWSCredentialsSecretReference struct {
	// Empty JSON tag is required to solve encountered struct field "" without JSON tag error.
	SecretReference `json:""`
```

2021-07-23 20:29 UTC, RedbackThomson commented on pkg/api/v1beta1/awspcaissuer_types.go
> +	Key string `json:"key,omitempty"`
No need to define this yourself. There already exists a type in the K8s core library for `SecretKeySelector` https://pkg.go.dev/k8s.io/api/core/v1#SecretKeySelector

2021-07-29 18:14 UTC, anbaig commented
Will take a look at PR after comments have been addressed

2021-07-29 23:17 UTC, kit837 commented
> Will take a look at PR after comments have been addressed

Hello @anbaig and @RedbackThomson -

Unfortunately @marshields is no longer working on this, and I'm not able to push to this branch.

I'm not sure of the best way to consolidate, but I opened up another PR to work on this feature: https://github.com/cert-manager/aws-privateca-issuer/pull/42

2021-07-29 23:33 UTC, RedbackThomson commented
> > Will take a look at PR after comments have been addressed
> 
> Hello @anbaig and @RedbackThomson -
> 
> Unfortunately @marshields is no longer working on this, and I'm not able to push to this branch.
> 
> I'm not sure of the best way to consolidate, but I opened up another PR to work on this feature: #42

Okay, no problem. Hopefully we can close this one up, and I'll switch over to the other PR.

2021-08-02 15:47 UTC, laebshade commented
Doesn't look like there's any way for me to personally close the PR; according to https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#marking-unfinished-pull-requests, it'll automatically close after 90 days.

2021-08-02 15:47 UTC, closed without merging